### ISSUE TITLE
Bad link in "How to use rclone with DreamObjects"

### ISSUE THREAD

**Issue by Bullfrog117** [dreamhost-knowledgebase/dreamhost-knowledgebase-articles#5]
https://help.dreamhost.com/hc/en-us/articles/226689248-How-to-use-rclone-with-DreamObjects

https://github.com/dreamhost-knowledgebase/dreamhost-knowledgebase-articles/blob/master/How%20to%20use%20rclone%20with%20DreamObjects.html

"Read more about DreamObject’s canned ACL <217590537>_."

Should be a link to https://help.dreamhost.com/hc/en-us/articles/217590537-How-To-Use-DreamObjects-S3-compatible-API

**Comment by cjdh** [comment]
Article has been updated.

**Comment by cjdh** [comment]
Article has been updated.
